const MARKER = "Generated by tate-rotate-controls.sh";
const BLOCK_START = "# BEGIN tate-rotate-controls";
const BLOCK_END = "# END tate-rotate-controls";

const REMAP_TEXT = `# ${MARKER}
input_player1_analog_dpad_mode = "3"
input_player1_btn_up = "7"
input_player1_btn_right = "5"
input_player1_btn_down = "6"
input_player1_btn_left = "4"
input_player1_btn_x = "8"
input_player1_btn_a = "0"
input_player1_btn_b = "1"
input_player1_btn_y = "9"
`;

const CUSTOM_BLOCK = `${BLOCK_START}
# Keep this filename as custom.sh: Batocera/KNULLI calls /userdata/system/custom.sh on boot.
case "$1" in
    start)
        if [ -f /userdata/system/scripts/tate-rotate-controls.sh ]; then
            /bin/bash /userdata/system/scripts/tate-rotate-controls.sh --refresh-all >/tmp/tate-rotate-controls.log 2>&1
        fi
        ;;
esac
${BLOCK_END}`;

const SHELL_SCRIPT = `#!/bin/bash

# Generate RetroArch game remaps for vertical/TATE arcade games.
# The remap rotates P1 D-pad, left-stick-as-D-pad, and ABXY clockwise.

BIOS_ROOT="\${BIOS_ROOT:-/userdata/bios}"
ROMS_ROOT="\${ROMS_ROOT:-/userdata/roms}"
REMAPPINGS_ROOT="\${REMAPPINGS_ROOT:-/userdata/system/configs/retroarch/config/remaps}"
CACHE_ROOT="\${CACHE_ROOT:-/userdata/system/.cache/tate-rotate-controls}"
MARKER="Generated by tate-rotate-controls.sh"

stream_metadata() {
    file="$1"

    case "$file" in
        *.gz)
            if command -v gzip >/dev/null 2>&1; then
                gzip -dc "$file"
            elif command -v zcat >/dev/null 2>&1; then
                zcat "$file"
            elif command -v busybox >/dev/null 2>&1; then
                busybox gzip -dc "$file"
            else
                return 1
            fi
            ;;
        *)
            cat "$file"
            ;;
    esac
}

build_vertical_cache() {
    dat_file="$1"
    cache_file="$2"

    [ -f "$dat_file" ] || return 1
    mkdir -p "$(dirname "$cache_file")" || return 1

    if [ -f "$cache_file" ] && [ "$cache_file" -nt "$dat_file" ]; then
        return 0
    fi

    tmp_file="\${cache_file}.$$"
    if stream_metadata "$dat_file" | awk '
        /<game name="/ {
            name = $0
            sub(/^.*<game name="/, "", name)
            sub(/".*$/, "", name)
            in_game = 1
            vertical = 0
        }
        in_game && /<video/ && /orientation="vertical"/ {
            vertical = 1
        }
        in_game && /<\\/game>/ {
            if (vertical && name != "") {
                print name
            }
            in_game = 0
            name = ""
            vertical = 0
        }
    ' > "$tmp_file"; then
        mv "$tmp_file" "$cache_file"
    else
        rm -f "$tmp_file"
        return 1
    fi
}

is_vertical_rom() {
    rom_name="$1"
    dat_file="$2"
    cache_file="$3"

    build_vertical_cache "$dat_file" "$cache_file" || return 1
    grep -Fxq "$rom_name" "$cache_file"
}

write_remap_contents() {
    cat <<EOF
# \${MARKER}
input_player1_analog_dpad_mode = "3"
input_player1_btn_up = "7"
input_player1_btn_right = "5"
input_player1_btn_down = "6"
input_player1_btn_left = "4"
input_player1_btn_x = "8"
input_player1_btn_a = "0"
input_player1_btn_b = "1"
input_player1_btn_y = "9"
EOF
}

write_clockwise_remap() {
    remap_core="$1"
    rom_name="$2"
    remap_dir="\${REMAPPINGS_ROOT}/\${remap_core}"
    remap_file="\${remap_dir}/\${rom_name}.rmp"

    mkdir -p "$remap_dir" || return 1

    if [ -f "$remap_file" ] && ! grep -Fq "$MARKER" "$remap_file"; then
        # A hand-made game remap already exists. Keep it as the user's override.
        return 0
    fi

    tmp_file="\${remap_file}.$$"
    write_remap_contents > "$tmp_file" || {
        rm -f "$tmp_file"
        return 1
    }

    if [ -f "$remap_file" ] && cmp -s "$tmp_file" "$remap_file"; then
        rm -f "$tmp_file"
        return 0
    fi

    mv "$tmp_file" "$remap_file"
}

generate_for_rom() {
    core="$1"
    rom_path="$2"

    rom_file="\${rom_path##*/}"
    rom_name="\${rom_file%.*}"
    extra_remap_core=""

    case "$core" in
        mame078plus|mame2003-plus|mame2003plus)
            remap_core="MAME 2003-Plus"
            dat_file="\${BIOS_ROOT}/mame2003-plus/mame2003-plus.xml.gz"
            cache_file="\${CACHE_ROOT}/mame2003-plus.vertical"
            ;;
        mame2010)
            remap_core="MAME 2010"
            dat_file="\${BIOS_ROOT}/mame2010/mame2010.xml.gz"
            cache_file="\${CACHE_ROOT}/mame2010.vertical"
            ;;
        fbneo|fbalpha)
            remap_core="FBNeo"
            extra_remap_core="FinalBurn Neo"
            dat_file="\${BIOS_ROOT}/fbneo/FinalBurn Neo (ClrMame Pro XML, Arcade only).dat"
            cache_file="\${CACHE_ROOT}/fbneo.vertical"
            ;;
        *)
            return 0
            ;;
    esac

    if is_vertical_rom "$rom_name" "$dat_file" "$cache_file"; then
        write_clockwise_remap "$remap_core" "$rom_name"
        [ -n "$extra_remap_core" ] && write_clockwise_remap "$extra_remap_core" "$rom_name"
    fi
}

refresh_folder() {
    core="$1"
    folder="$2"

    [ -d "$folder" ] || return 0

    for rom_path in "$folder"/*.zip "$folder"/*.7z; do
        [ -e "$rom_path" ] || continue
        generate_for_rom "$core" "$rom_path"
    done
}

refresh_all() {
    refresh_folder "mame078plus" "\${ROMS_ROOT}/mame"
    refresh_folder "mame2010" "\${ROMS_ROOT}/mame"
    refresh_folder "fbneo" "\${ROMS_ROOT}/fbneo"
}

case "$1" in
    --refresh-all|refresh-all)
        refresh_all
        ;;
    gameStart)
        emulator="$3"
        core="$4"
        rom_path="$5"
        [ "$emulator" = "libretro" ] || exit 0
        [ -n "$rom_path" ] || exit 0
        generate_for_rom "$core" "$rom_path"
        ;;
esac

exit 0
`;

const CORE_CONFIGS = [
  {
    id: "mame2003-plus",
    label: "MAME 2003-Plus",
    romPath: ["roms", "mame"],
    datPath: ["bios", "mame2003-plus", "mame2003-plus.xml.gz"],
    remapCores: ["MAME 2003-Plus"],
  },
  {
    id: "mame2010",
    label: "MAME 2010",
    romPath: ["roms", "mame"],
    datPath: ["bios", "mame2010", "mame2010.xml.gz"],
    remapCores: ["MAME 2010"],
  },
  {
    id: "fbneo",
    label: "FinalBurn Neo",
    romPath: ["roms", "fbneo"],
    datPath: ["bios", "fbneo", "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat"],
    remapCores: ["FBNeo", "FinalBurn Neo"],
  },
];

const state = {
  rootHandle: null,
  analysis: null,
  busy: false,
};

const els = {};

document.addEventListener("DOMContentLoaded", () => {
  for (const id of [
    "unsupported",
    "chooseButton",
    "rescanButton",
    "installButton",
    "installBootHook",
    "generateRemaps",
    "statusBadge",
    "targetLabel",
    "summary",
    "planList",
    "log",
  ]) {
    els[id] = document.getElementById(id);
  }

  if (!("showDirectoryPicker" in window) || !window.isSecureContext) {
    els.unsupported.classList.remove("hidden");
  }

  els.chooseButton.addEventListener("click", chooseFolder);
  els.rescanButton.addEventListener("click", () => analyzeSelectedFolder());
  els.installButton.addEventListener("click", installChanges);
  els.installBootHook.addEventListener("change", () => analyzeSelectedFolder());
  els.generateRemaps.addEventListener("change", () => analyzeSelectedFolder());
});

async function chooseFolder() {
  if (!("showDirectoryPicker" in window)) {
    setError("This browser does not expose folder access to web pages.");
    return;
  }

  try {
    state.rootHandle = await window.showDirectoryPicker({
      id: "batocera-share",
      mode: "readwrite",
    });
    els.targetLabel.textContent = state.rootHandle.name;
    log(`Selected folder: ${state.rootHandle.name}`);
    await analyzeSelectedFolder();
  } catch (error) {
    if (error.name !== "AbortError") {
      setError(error.message);
      log(`Folder selection failed: ${error.message}`);
    }
  }
}

async function analyzeSelectedFolder(options = {}) {
  if (!state.rootHandle || (state.busy && !options.force)) return;

  setBusy(true);
  setStatus("Scanning", "warn");

  const plan = {
    rootName: state.rootHandle.name,
    options: readOptions(),
    errors: [],
    warnings: [],
    systemFiles: [],
    cores: [],
    remaps: [],
  };

  try {
    const granted = await verifyPermission(state.rootHandle);
    if (!granted) {
      plan.errors.push("Folder write permission was not granted.");
    }

    await validateShareFolder(plan);

    if (!plan.errors.length) {
      await analyzeSystemFiles(plan);
      if (plan.options.generateRemaps) {
        await analyzeRemaps(plan);
      }
    }
  } catch (error) {
    plan.errors.push(error.message);
    log(`Scan failed: ${error.message}`);
  }

  state.analysis = plan;
  renderPlan(plan);
  setBusy(false);
}

async function installChanges() {
  if (!state.analysis || state.busy || state.analysis.errors.length) return;

  setBusy(true);
  setStatus("Installing", "warn");
  const plan = state.analysis;
  const stamp = timestamp();
  let written = 0;
  let backedUp = 0;

  try {
    for (const file of plan.systemFiles) {
      if (file.action !== "create" && file.action !== "update") continue;
      if (file.currentText != null) {
        await backupFile(file.pathParts, file.currentText, stamp);
        backedUp += 1;
      }
      await writeTextPath(file.pathParts, file.desiredText);
      written += 1;
      log(`${file.action}: ${formatPath(file.pathParts)}`);
    }

    for (const remap of plan.remaps) {
      if (remap.action !== "create" && remap.action !== "update") continue;
      await writeTextPath(remap.pathParts, REMAP_TEXT);
      written += 1;
    }

    log(`Install complete. Wrote ${written} file(s), created ${backedUp} backup(s).`);
    await analyzeSelectedFolder({ force: true });
    setStatus("Installed", "ready");
  } catch (error) {
    setError(error.message);
    log(`Install failed: ${error.message}`);
  } finally {
    setBusy(false);
  }
}

async function validateShareFolder(plan) {
  const systemDir = await tryGetDirectory(["system"]);
  const romsDir = await tryGetDirectory(["roms"]);

  if (!systemDir || !romsDir) {
    plan.errors.push("The selected folder does not look like the root of a Batocera SHARE drive.");
    return;
  }

  const conf = await tryGetFile(["system", "batocera.conf"]);
  if (!conf) {
    plan.warnings.push("system/batocera.conf was not found. The tool can still install, but double-check the selected folder.");
  }
}

async function analyzeSystemFiles(plan) {
  const scriptText = withFinalLf(SHELL_SCRIPT);
  const scriptPath = ["system", "scripts", "tate-rotate-controls.sh"];
  plan.systemFiles.push(await planTextFile("Feature script", scriptPath, scriptText));

  if (plan.options.installBootHook) {
    const customPath = ["system", "custom.sh"];
    const current = await readExistingText(customPath);
    const desired = patchCustomSh(current.exists ? current.text : null);
    plan.systemFiles.push(planTextFileFromCurrent("Boot hook", customPath, desired, current));
  } else {
    plan.systemFiles.push({
      label: "Boot hook",
      pathParts: ["system", "custom.sh"],
      action: "skip",
      detail: "Option off",
    });
  }
}

async function analyzeRemaps(plan) {
  for (const config of CORE_CONFIGS) {
    const corePlan = {
      label: config.label,
      romPath: formatPath(config.romPath),
      datPath: formatPath(config.datPath),
      roms: 0,
      vertical: 0,
      planned: 0,
      status: "ok",
      note: "",
    };

    const romDir = await tryGetDirectory(config.romPath);
    const datFile = await tryGetFile(config.datPath);

    if (!romDir) {
      corePlan.status = "skip";
      corePlan.note = "ROM folder missing";
      plan.cores.push(corePlan);
      continue;
    }

    if (!datFile) {
      corePlan.status = "skip";
      corePlan.note = "metadata file missing";
      plan.cores.push(corePlan);
      continue;
    }

    let metadataText = "";
    try {
      metadataText = await readMetadataText(datFile);
    } catch (error) {
      corePlan.status = "error";
      corePlan.note = error.message;
      plan.cores.push(corePlan);
      continue;
    }

    const verticalNames = parseVerticalGameNames(metadataText);
    const roms = await listRomFiles(romDir);
    const verticalRoms = roms.filter((rom) => verticalNames.has(rom.lookupName));

    corePlan.roms = roms.length;
    corePlan.vertical = verticalRoms.length;

    for (const rom of verticalRoms) {
      for (const remapCore of config.remapCores) {
        const remap = await planRemap(config.label, remapCore, rom.romName);
        plan.remaps.push(remap);
        corePlan.planned += 1;
      }
    }

    plan.cores.push(corePlan);
  }
}

async function planRemap(source, remapCore, romName) {
  const pathParts = [
    "system",
    "configs",
    "retroarch",
    "config",
    "remaps",
    remapCore,
    `${romName}.rmp`,
  ];

  const current = await readExistingText(pathParts);
  const item = {
    source,
    label: `${remapCore} / ${romName}`,
    pathParts,
    currentText: current.exists ? current.text : null,
    desiredText: REMAP_TEXT,
    action: "create",
  };

  if (!current.exists) return item;
  if (!current.text.includes(MARKER)) {
    item.action = "skip-handmade";
    return item;
  }

  item.action = sameText(current.text, REMAP_TEXT) ? "no-change" : "update";
  return item;
}

async function planTextFile(label, pathParts, desiredText) {
  const current = await readExistingText(pathParts);
  return planTextFileFromCurrent(label, pathParts, desiredText, current);
}

function planTextFileFromCurrent(label, pathParts, desiredText, current) {
  const item = {
    label,
    pathParts,
    currentText: current.exists ? current.text : null,
    desiredText,
    action: "create",
  };

  if (!current.exists) return item;
  item.action = sameText(current.text, desiredText) ? "no-change" : "update";
  return item;
}

function patchCustomSh(existingText) {
  let text = existingText && existingText.trim()
    ? normalizeLf(existingText)
    : "#!/bin/bash\n\nexit 0\n";

  if (!text.startsWith("#!")) {
    text = `#!/bin/bash\n\n${text}`;
  }

  const blockPattern = new RegExp(`${escapeRegExp(BLOCK_START)}[\\s\\S]*?${escapeRegExp(BLOCK_END)}\\n?`, "m");
  if (blockPattern.test(text)) {
    return withFinalLf(text.replace(blockPattern, `${CUSTOM_BLOCK}\n`));
  }

  const lines = normalizeLf(text).split("\n");
  let insertAt = -1;
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    if (/^\s*exit(?:\s+\d+)?\s*$/.test(lines[i])) {
      insertAt = i;
      break;
    }
  }

  const blockLines = ["", ...CUSTOM_BLOCK.split("\n"), ""];
  if (insertAt >= 0) {
    lines.splice(insertAt, 0, ...blockLines);
  } else {
    if (lines[lines.length - 1] !== "") lines.push("");
    lines.push(...CUSTOM_BLOCK.split("\n"), "", "exit 0");
  }

  return withFinalLf(lines.join("\n"));
}

function parseVerticalGameNames(text) {
  const names = new Set();
  const gamePattern = /<game\b([^>]*)>([\s\S]*?)<\/game>/gi;
  let match;

  while ((match = gamePattern.exec(text)) !== null) {
    const attrs = match[1];
    const body = match[2];
    if (!/<video\b[^>]*\borientation="vertical"/i.test(body)) continue;

    const nameMatch = /\bname="([^"]+)"/i.exec(attrs);
    if (nameMatch) {
      names.add(decodeXml(nameMatch[1]).toLowerCase());
    }
  }

  return names;
}

async function listRomFiles(dirHandle) {
  const roms = [];
  for await (const handle of dirHandle.values()) {
    if (handle.kind !== "file") continue;
    if (!/\.(zip|7z)$/i.test(handle.name)) continue;
    const romName = handle.name.replace(/\.(zip|7z)$/i, "");
    roms.push({
      fileName: handle.name,
      romName,
      lookupName: romName.toLowerCase(),
    });
  }
  roms.sort((a, b) => a.romName.localeCompare(b.romName));
  return roms;
}

async function readMetadataText(fileHandle) {
  const file = await fileHandle.getFile();
  if (!file.name.toLowerCase().endsWith(".gz")) {
    return file.text();
  }

  if (!("DecompressionStream" in window)) {
    throw new Error("This browser cannot read gzip metadata. The device script can still refresh on boot.");
  }

  const stream = file.stream().pipeThrough(new DecompressionStream("gzip"));
  return new Response(stream).text();
}

async function verifyPermission(handle) {
  const options = { mode: "readwrite" };
  if ((await handle.queryPermission(options)) === "granted") return true;
  return (await handle.requestPermission(options)) === "granted";
}

async function tryGetDirectory(pathParts) {
  try {
    return await getDirectory(pathParts, false);
  } catch (error) {
    return null;
  }
}

async function getDirectory(pathParts, create) {
  let dir = state.rootHandle;
  for (const part of pathParts) {
    dir = await dir.getDirectoryHandle(part, { create });
  }
  return dir;
}

async function tryGetFile(pathParts) {
  try {
    return await getFile(pathParts, false);
  } catch (error) {
    return null;
  }
}

async function getFile(pathParts, create) {
  const fileName = pathParts[pathParts.length - 1];
  const dirParts = pathParts.slice(0, -1);
  const dir = await getDirectory(dirParts, create);
  return dir.getFileHandle(fileName, { create });
}

async function readExistingText(pathParts) {
  const handle = await tryGetFile(pathParts);
  if (!handle) return { exists: false, text: null };
  const file = await handle.getFile();
  return { exists: true, text: await file.text() };
}

async function writeTextPath(pathParts, text) {
  const handle = await getFile(pathParts, true);
  const writable = await handle.createWritable();
  await writable.write(withFinalLf(text));
  await writable.close();
}

async function writeRawTextPath(pathParts, text) {
  const handle = await getFile(pathParts, true);
  const writable = await handle.createWritable();
  await writable.write(text);
  await writable.close();
}

async function backupFile(pathParts, text, stamp) {
  const name = pathParts[pathParts.length - 1];
  const backupParts = pathParts.slice(0, -1).concat(`${name}.tate-backup-${stamp}`);
  await writeRawTextPath(backupParts, text);
  log(`backup: ${formatPath(backupParts)}`);
}

function renderPlan(plan) {
  els.planList.replaceChildren();

  if (plan.errors.length) {
    setStatus("Needs Attention", "error");
  } else if (plan.warnings.length) {
    setStatus("Review", "warn");
  } else {
    setStatus("Ready", "ready");
  }

  const counts = summarize(plan);
  renderSummary(counts);

  if (plan.errors.length || plan.warnings.length) {
    const section = makeSection("Messages");
    for (const error of plan.errors) addRow(section, "Error", error, "error", "error");
    for (const warning of plan.warnings) addRow(section, "Warning", warning, "skip", "skip");
    els.planList.appendChild(section);
  }

  const systemSection = makeSection("System Files");
  for (const file of plan.systemFiles) {
    addRow(systemSection, file.label, formatPath(file.pathParts), file.action, actionTone(file.action));
  }
  els.planList.appendChild(systemSection);

  if (plan.cores.length) {
    const coreSection = makeSection("Arcade Metadata");
    for (const core of plan.cores) {
      const detail = core.note || `${core.vertical} vertical of ${core.roms} ROM(s), ${core.planned} remap file(s)`;
      addRow(coreSection, core.label, detail, core.status, actionTone(core.status));
    }
    els.planList.appendChild(coreSection);
  }

  if (plan.remaps.length) {
    const remapSection = makeSection("Remap Preview");
    const rows = document.createElement("div");
    rows.className = "rows compact-list";
    for (const remap of plan.remaps.slice(0, 350)) {
      rows.appendChild(makeRow(remap.source, formatPath(remap.pathParts), remap.action, actionTone(remap.action)));
    }
    if (plan.remaps.length > 350) {
      rows.appendChild(makeRow("Preview trimmed", `${plan.remaps.length - 350} more remap file(s) are planned`, "info", "info"));
    }
    remapSection.appendChild(rows);
    els.planList.appendChild(remapSection);
  }

  els.rescanButton.disabled = !state.rootHandle || state.busy;
  els.installButton.disabled = state.busy || plan.errors.length > 0 || !hasWritableChanges(plan);
}

function renderSummary(counts) {
  els.summary.className = "summary";
  els.summary.replaceChildren(
    metric("System writes", counts.systemWrites),
    metric("Remap creates", counts.remapCreates),
    metric("Remap updates", counts.remapUpdates),
    metric("Preserved", counts.preserved),
  );
}

function summarize(plan) {
  return {
    systemWrites: plan.systemFiles.filter((item) => item.action === "create" || item.action === "update").length,
    remapCreates: plan.remaps.filter((item) => item.action === "create").length,
    remapUpdates: plan.remaps.filter((item) => item.action === "update").length,
    preserved: plan.remaps.filter((item) => item.action === "skip-handmade" || item.action === "no-change").length,
  };
}

function hasWritableChanges(plan) {
  return [...plan.systemFiles, ...plan.remaps].some((item) => item.action === "create" || item.action === "update");
}

function metric(label, value) {
  const node = document.createElement("div");
  node.className = "metric";
  const strong = document.createElement("strong");
  strong.textContent = value;
  const span = document.createElement("span");
  span.textContent = label;
  node.append(strong, span);
  return node;
}

function makeSection(title) {
  const section = document.createElement("section");
  section.className = "section";
  const heading = document.createElement("h2");
  heading.textContent = title;
  const rows = document.createElement("div");
  rows.className = "rows";
  section.append(heading, rows);
  return section;
}

function addRow(section, label, detail, action, tone) {
  section.querySelector(".rows").appendChild(makeRow(label, detail, action, tone));
}

function makeRow(label, detail, action, tone) {
  const row = document.createElement("div");
  row.className = "row";
  const labelNode = document.createElement("strong");
  labelNode.textContent = label;
  const detailNode = document.createElement("span");
  detailNode.className = "path";
  detailNode.textContent = detail;
  const pill = document.createElement("span");
  pill.className = `pill ${tone || ""}`;
  pill.textContent = actionLabel(action);
  row.append(labelNode, detailNode, pill);
  return row;
}

function setBusy(isBusy) {
  state.busy = isBusy;
  els.chooseButton.disabled = isBusy;
  els.rescanButton.disabled = isBusy || !state.rootHandle;
  els.installButton.disabled = isBusy || !state.analysis || state.analysis.errors.length > 0 || !hasWritableChanges(state.analysis);
}

function setStatus(text, tone) {
  els.statusBadge.textContent = text;
  els.statusBadge.className = `badge ${tone || ""}`;
}

function setError(message) {
  setStatus("Error", "error");
  els.summary.className = "summary empty";
  els.summary.textContent = message;
}

function log(message) {
  const line = document.createElement("p");
  line.textContent = `[${new Date().toLocaleTimeString()}] ${message}`;
  els.log.prepend(line);
}

function readOptions() {
  return {
    installBootHook: els.installBootHook.checked,
    generateRemaps: els.generateRemaps.checked,
  };
}

function normalizeLf(text) {
  return String(text).replace(/\r\n?/g, "\n");
}

function withFinalLf(text) {
  return normalizeLf(text).replace(/\n*$/, "\n");
}

function sameText(a, b) {
  return withFinalLf(a) === withFinalLf(b);
}

function formatPath(pathParts) {
  return pathParts.join("/");
}

function actionLabel(action) {
  const labels = {
    create: "create",
    update: "update",
    "no-change": "ok",
    "skip-handmade": "keep existing",
    skip: "skip",
    ok: "ok",
    error: "error",
    info: "info",
  };
  return labels[action] || action;
}

function actionTone(action) {
  if (action === "create" || action === "update") return action;
  if (action === "skip" || action === "skip-handmade") return "skip";
  if (action === "error") return "error";
  if (action === "ok" || action === "no-change") return "";
  return "info";
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function decodeXml(text) {
  return text
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function timestamp() {
  const d = new Date();
  const pad = (value) => String(value).padStart(2, "0");
  return [
    d.getFullYear(),
    pad(d.getMonth() + 1),
    pad(d.getDate()),
    "-",
    pad(d.getHours()),
    pad(d.getMinutes()),
    pad(d.getSeconds()),
  ].join("");
}
